### ISSUE TITLE
Hallo ich brauche hilfe!

### ISSUE THREAD

**Issue by FreshK11** [buttenberger-squad/quizzle#2]
Hallo, ich habe ein Problem mit meinem ding. Danke für eure hilfe.

**Comment by choppey** [comment]
Was ist denn dein Anliegen?

**Comment by FreshK11** [comment]
Mein Code funktioniert nicht. Eigentlich sollte er einen 3x3 Rubix Cube anzeigen, shuffeln und dann lösen aber irgendwie geht das nicht.
Hier ein ausschnitt aus meinem Programm..

`<html>`
    `<body>`
        Hello world
    `</body>`
`</html>`

**Comment by choppey** [comment]
> Mein Code funktioniert nicht. Eigentlich sollte er einen 3x3 Rubix Cube anzeigen, shuffeln und dann lösen aber irgendwie geht das nicht.
> Hier ein ausschnitt aus meinem Programm..
> 
> `<html>`
> `<body>`
> Hello world
> `</body>`
> `</html>`

Versuch dein Laptop neu zu starten

**Comment by FreshK11** [comment]
> > Mein Code funktioniert nicht. Eigentlich sollte er einen 3x3 Rubix Cube anzeigen, shuffeln und dann lösen aber irgendwie geht das nicht.
> > Hier ein ausschnitt aus meinem Programm..
> > `<html>`
> > `<body>`
> > Hello world
> > `</body>`
> > `</html>`
> 
> Versuch dein Laptop neu zu starten

Danke, werde ich machen.
